/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetIUT.forms;

import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Kazed
 */
public class ConnectionParamsPanel extends javax.swing.JPanel {
    private final HashMap<String, String> params;
    /**
     * Creates new form ConnectionParams
     * @param params
     */
    public ConnectionParamsPanel(HashMap<String, String> params) {
        initComponents();
        this.params = params;
        if(!params.isEmpty()) {
            txtHost.setText(params.get("Host"));
            txtPort.setValue(params.get("Port"));
            txtDb.setText(params.get("Database"));
        }
    }
    
    public JTextField getInput(String param) {
        switch(param) {
            case "Host" : return txtHost;
            case "Port" : return txtPort;
            case "Database" : return txtDb;
            default : return null;
        }
    }
    
    public JButton getButton() {
        return btnConfirm;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHost = new javax.swing.JLabel();
        lblPort = new javax.swing.JLabel();
        lblDb = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        txtDb = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        txtPort = new javax.swing.JFormattedTextField();

        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(316, 216));
        setMinimumSize(new java.awt.Dimension(316, 216));
        setPreferredSize(new java.awt.Dimension(316, 216));

        lblHost.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblHost.setText("Hôte");

        lblPort.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPort.setText("Port");

        lblDb.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDb.setText("Base de données");

        txtHost.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtHost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHost.setMaximumSize(new java.awt.Dimension(96, 20));
        txtHost.setMinimumSize(new java.awt.Dimension(96, 20));
        txtHost.setPreferredSize(new java.awt.Dimension(96, 20));

        txtDb.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDb.setMaximumSize(new java.awt.Dimension(96, 20));
        txtDb.setMinimumSize(new java.awt.Dimension(96, 20));
        txtDb.setPreferredSize(new java.awt.Dimension(96, 20));

        btnConfirm.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnConfirm.setText("Confirmer");
        btnConfirm.setMaximumSize(new java.awt.Dimension(96, 32));
        btnConfirm.setMinimumSize(new java.awt.Dimension(96, 32));
        btnConfirm.setPreferredSize(new java.awt.Dimension(96, 32));

        txtPort.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDb)
                    .addComponent(lblHost)
                    .addComponent(lblPort))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPort, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHost)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPort)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDb)
                    .addComponent(txtDb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel lblDb;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblPort;
    private javax.swing.JTextField txtDb;
    private javax.swing.JTextField txtHost;
    private javax.swing.JFormattedTextField txtPort;
    // End of variables declaration//GEN-END:variables
}
