/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetIUT.forms;

import ProjetIUT.classesConnexion.Connexion;
import ProjetIUT.classesConnexion.ConnexionMySQL;
import ProjetIUT.classesConnexion.ConnexionOracle;
import ProjetIUT.gestFichiers.ConnectionDataJSON;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author Kazed
 */
public class ConnectionPanel extends javax.swing.JPanel {
    private final ConnectionDataJSON json;
    private ResultSet donnees;
    private DatabaseMetaData metadata;

    /**
     * Creates new form FormConnect
     */
    public ConnectionPanel() {
        initComponents();
        json = new ConnectionDataJSON();
        if(json.getSGBD() != null) cbxSGBD.setSelectedItem(json.getSGBD());
    }

    public boolean isURLSet() {
        return !(json.getParams().isEmpty());
    }

    public JDialog createParamsDialog() {
        final JDialog dialog = new JDialog();
        dialog.setTitle("Paramètres de l'URL");
        dialog.setModal(true);
        dialog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ConnectionParamsPanel content = new ConnectionParamsPanel(json.getParams());

        //Sauvegarde les paramètres dans un fichier JSON et ferme le JDialog
        content.getButton().addActionListener((ActionEvent e) -> {
            json.setParam("Host", content.getInput("Host").getText());
            json.setParam("Port", content.getInput("Port").getText());
            json.setParam("Database", content.getInput("Database").getText());
            json.save();
            dialog.dispose();
        });
        dialog.setContentPane(content);
        dialog.setResizable(false);
        dialog.pack();
        return dialog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConnect = new javax.swing.JButton();
        lblSGBD = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        cbxSGBD = new javax.swing.JComboBox<>();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnConnectionParams = new javax.swing.JButton();

        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(322, 252));
        setMinimumSize(new java.awt.Dimension(322, 252));

        btnConnect.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnConnect.setText("Se connecter");
        btnConnect.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConnect.setMaximumSize(new java.awt.Dimension(112, 32));
        btnConnect.setMinimumSize(new java.awt.Dimension(112, 32));
        btnConnect.setPreferredSize(new java.awt.Dimension(112, 32));
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        lblSGBD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSGBD.setText("SGBD");

        lblUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUser.setText("Utilisateur");

        lblPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPassword.setText("Mot de passe");

        cbxSGBD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbxSGBD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oracle", "MySQL" }));
        cbxSGBD.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbxSGBD.setLightWeightPopupEnabled(false);
        cbxSGBD.setMaximumSize(new java.awt.Dimension(96, 20));
        cbxSGBD.setMinimumSize(new java.awt.Dimension(96, 20));
        cbxSGBD.setPreferredSize(new java.awt.Dimension(96, 20));

        txtUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtUser.setMaximumSize(new java.awt.Dimension(96, 20));
        txtUser.setMinimumSize(new java.awt.Dimension(96, 20));
        txtUser.setPreferredSize(new java.awt.Dimension(96, 20));

        txtPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPassword.setMaximumSize(new java.awt.Dimension(96, 20));
        txtPassword.setMinimumSize(new java.awt.Dimension(96, 20));
        txtPassword.setPreferredSize(new java.awt.Dimension(96, 20));

        btnConnectionParams.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnConnectionParams.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/settings.png"))); // NOI18N
        btnConnectionParams.setToolTipText("Options avancées");
        btnConnectionParams.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConnectionParams.setMaximumSize(new java.awt.Dimension(32, 32));
        btnConnectionParams.setMinimumSize(new java.awt.Dimension(32, 32));
        btnConnectionParams.setPreferredSize(new java.awt.Dimension(32, 32));
        btnConnectionParams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectionParamsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblSGBD)
                                .addGap(96, 96, 96)
                                .addComponent(cbxSGBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPassword))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnConnectionParams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btnConnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConnectionParams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSGBD)
                    .addComponent(cbxSGBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnConnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        btnConnectionParams.setBorder(BorderFactory.createEmptyBorder());
        btnConnectionParams.setContentAreaFilled(false);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        String sgbd = cbxSGBD.getSelectedItem().toString();
        json.setParam("SGBD", sgbd);
        Connexion c;
        //Connexion à la BDD en fonction du SGBD choisi
        switch(sgbd) {
            case "MySQL" :
                c = new ConnexionMySQL(json.getParams().get("Host"), Integer.parseInt(json.getParams().get("Port")), json.getParams().get("Database"));
                break;
            default :
                c = new ConnexionOracle(json.getParams().get("Host"), Integer.parseInt(json.getParams().get("Port")), json.getParams().get("Database"));
        }

        //Si la connexion est effectuée, sauvegarde le SGBD dans le JSON
        //et switche sur le JPanel VisualizationPanel
        if(c.connexion(c.getURL(), txtUser.getText(), String.valueOf(txtPassword.getPassword()))) {
            try {
                c.prepareStatements();
                json.save();
                MainFrame f = (MainFrame)SwingUtilities.getRoot(this);
                JPanel panel = (JPanel)f.getContentPane();
                CardLayout layout = (CardLayout)panel.getLayout();
                layout.next(panel);
                f.setCurrentCard();
                VisualizationPanel vp = (VisualizationPanel)f.getCurrentCard();
                vp.connect(c);
            }
            catch(SQLException e) {

            }
        }
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnConnectionParamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectionParamsActionPerformed
        createParamsDialog().setVisible(true);
    }//GEN-LAST:event_btnConnectionParamsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnConnectionParams;
    private javax.swing.JComboBox<String> cbxSGBD;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSGBD;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
