package ProjetIUT.forms;

import java.awt.Component;
import java.awt.Font;
import javax.swing.JPanel;

// @author Kazed
public class MainFrame extends javax.swing.JFrame {
    private final Font font = new Font("Arial", 0, 12);
    private JPanel currentCard;

    public MainFrame() {
        initComponents();
    }

    public JPanel getCurrentCard() {
        return currentCard;
    }

    public void setCurrentCard() {
        JPanel card = null;
        for (Component comp : getContentPane().getComponents()) {
             if (comp.isVisible() == true) {
                card = (JPanel)comp;
            }
        }
        currentCard = card;
        String title = null;
        switch(currentCard.getName()) {
            case "Connection":
                title = "Connexion";
                setResizable(false);
                break;
            case "Visualization":
                title = "Visualization";
                setResizable(true);
                break;
            default:
                break;
        }
        setTitle(title);
        getContentPane().setPreferredSize(currentCard.getPreferredSize());
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
