package sgbd.forms;

// @author Kazed

import java.util.Locale;
import javax.swing.JPanel;
import sgbd.forms.cardPanels.ConnectionPanel;


public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {
        initComponents();
    }
    
    public CardLayoutPanel getMainPanel() {
        return panel;
    }
    
    public JPanel getCardPanel(String s) {
        JPanel cardPanel = null;
        switch(s.toLowerCase(Locale.ROOT)) {
            case "first":
                cardPanel = panel.firstCard();
                break;
            case "last":
                cardPanel = panel.lastCard();
                break;
            case "next":
                cardPanel = panel.nextCard();
                break;
            case "previous":
                cardPanel = panel.previousCard();
                break;
        }
        if(cardPanel != null) {
            setVisible(false);
            getContentPane().setPreferredSize(cardPanel.getPreferredSize());
            switch(cardPanel.getName()) {
            case "visualizationPanel":
                setTitle("Visualization");
                setResizable(true);
                break;
            default:
                setTitle("Connexion");
                setResizable(false);
                break;
            }
            pack();
            setLocationRelativeTo(null);
            setVisible(true);
        }
        return cardPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new sgbd.forms.CardLayoutPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("mainFrame"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ConnectionPanel coPanel = (ConnectionPanel)getCardPanel("first");
        if(!coPanel.isURLSet()) {
            coPanel.showParamsDialog();
        }
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sgbd.forms.CardLayoutPanel panel;
    // End of variables declaration//GEN-END:variables
}
