/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgbd.forms.dialogs;

import java.awt.Component;
import java.awt.Cursor;
import java.awt.Font;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.text.Document;

/**
 *
 * @author Kazed
 */
public class ConnectionParamsDialog extends javax.swing.JPanel {
    private final HashMap<String, String> params;
    /**
     * Creates new form ConnectionParams
     * @param params
     */
    public ConnectionParamsDialog(HashMap<String, String> params) {
        initComponents();
        this.params = params;
        if(!params.isEmpty()) {
            txtHost.setText(params.get("Host"));
            txtPort.setText(params.get("Port"));
            txtDb.setText(params.get("Database"));
            comboBoxSGBD.setSelectedItem(params.get("SGBD"));
        }
    }
    
    public String getInput(String param) {
        switch(param) {
            case "Host" : return txtHost.getText();
            case "Port" : return txtPort.getText();
            case "Database" : return txtDb.getText();
            case "SGBD" : return comboBoxSGBD.getSelectedItem().toString();
            default : return null;
        }
    }
    
    public JButton getButton(String s) {
        switch(s.toLowerCase()) {
            case "confirm":
                return btnConfirm;
            case "cancel":
                return btnCancel;
            default:
                return null;
        }
    }
    
    public void setComponentsParams(Font f) {
        for(Component comp : lpnContainer.getComponents()) {
            boolean setFont = true;
            switch(comp.getClass().getSimpleName()) {
                case "JButton":
                    if(comp.getName().contains("Error")) {
                        comp.setVisible(false);
                    }
                    else comp.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                    break;
                case "JTextField":     
                    break;
                default:
                    break;
            }
            if(setFont)comp.setFont(f);
        }
    }
    
    /**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lpnContainer = new javax.swing.JLayeredPane();
        lblHost = new javax.swing.JLabel();
        lblPort = new javax.swing.JLabel();
        lblDb = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        txtPort = new javax.swing.JTextField();
        txtDb = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboBoxSGBD = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(320, 218));

        lpnContainer.setPreferredSize(new java.awt.Dimension(226, 250));

        lblHost.setText("Hôte");

        lblPort.setText("Port");

        lblDb.setText("Base de données");

        txtHost.setPreferredSize(new java.awt.Dimension(96, 19));

        txtPort.setColumns(5);
        txtPort.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtDb.setPreferredSize(new java.awt.Dimension(96, 19));

        btnCancel.setText("Annuler");
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.setPreferredSize(new java.awt.Dimension(96, 32));

        btnConfirm.setText("Confirmer");
        btnConfirm.setName("btnConfirm"); // NOI18N
        btnConfirm.setPreferredSize(new java.awt.Dimension(96, 32));

        jLabel1.setText("SGDB");

        comboBoxSGBD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oracle", "MySQL" }));

        lpnContainer.setLayer(lblHost, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnContainer.setLayer(lblPort, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnContainer.setLayer(lblDb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnContainer.setLayer(txtHost, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnContainer.setLayer(txtPort, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnContainer.setLayer(txtDb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnContainer.setLayer(btnCancel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnContainer.setLayer(btnConfirm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnContainer.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnContainer.setLayer(comboBoxSGBD, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lpnContainerLayout = new javax.swing.GroupLayout(lpnContainer);
        lpnContainer.setLayout(lpnContainerLayout);
        lpnContainerLayout.setHorizontalGroup(
            lpnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpnContainerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(lpnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPort)
                    .addComponent(lblHost)
                    .addComponent(lblDb)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lpnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDb, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(txtHost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxSGBD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpnContainerLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        lpnContainerLayout.setVerticalGroup(
            lpnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpnContainerLayout.createSequentialGroup()
                .addGroup(lpnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lpnContainerLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(comboBoxSGBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpnContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(19, 19, 19)
                        .addComponent(lblHost)))
                .addGap(14, 14, 14)
                .addGroup(lpnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPort)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lpnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDb)
                    .addComponent(txtDb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(lpnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lpnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lpnContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> comboBoxSGBD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDb;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLayeredPane lpnContainer;
    private javax.swing.JTextField txtDb;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables
}
