/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgbd.forms.dialogs;

import javax.swing.JTable;
import javax.swing.table.TableColumn;
import sgbd.controllers.Controller;
import sgbd.database.Table;

/**
 *
 * @author Alexandre
 */
public class TableDonneesCRUDPanel extends javax.swing.JPanel {

    /**
     * Creates new form TableDonneesCRUDPanel
     * @param ctr
     * @param laTable
     */
    public TableDonneesCRUDPanel(Controller ctr,Table laTable) {
        initComponents();
        TableColumn col;
        int longueurArrayListDeLaTable = laTable.attributes().size();
        for(int i=0 ; i<longueurArrayListDeLaTable ; i++)
        {
            col = new TableColumn(i);
            col.setHeaderValue(laTable.attributes().get(i).getName());
            jTableDonneesCRUD.addColumn(col);
        }
        labelTableName.setText(laTable.getName());
        labelTableName2.setText(laTable.getName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNomDeLaTable = new java.awt.Label();
        labelTableName = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDonneesCRUD = new javax.swing.JTable();
        labelFiltreSELECT = new java.awt.Label();
        jButtonLancerSELECT = new javax.swing.JButton();
        checkboxSelectAll = new java.awt.Checkbox();
        labelSelectFrom = new java.awt.Label();
        labelTableName2 = new java.awt.Label();
        labelSelectFromWhere = new java.awt.Label();

        labelNomDeLaTable.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelNomDeLaTable.setText("Nom de la table:");

        labelTableName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelTableName.setText("TABLE_NAME");

        jTableDonneesCRUD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableDonneesCRUD);

        labelFiltreSELECT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelFiltreSELECT.setText("Select");

        jButtonLancerSELECT.setText("Lancer Recherche");

        checkboxSelectAll.setLabel("*  (tous les attributs)");

        labelSelectFrom.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelSelectFrom.setText("From");

        labelTableName2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelTableName2.setText("TABLE_NAME");

        labelSelectFromWhere.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelSelectFromWhere.setText("Where");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelNomDeLaTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelTableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelFiltreSELECT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(checkboxSelectAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButtonLancerSELECT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSelectFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTableName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelSelectFromWhere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNomDeLaTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelFiltreSELECT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkboxSelectAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelSelectFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTableName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSelectFromWhere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLancerSELECT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkboxSelectAll;
    private javax.swing.JButton jButtonLancerSELECT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDonneesCRUD;
    private java.awt.Label labelFiltreSELECT;
    private java.awt.Label labelNomDeLaTable;
    private java.awt.Label labelSelectFrom;
    private java.awt.Label labelSelectFromWhere;
    private java.awt.Label labelTableName;
    private java.awt.Label labelTableName2;
    // End of variables declaration//GEN-END:variables
}
