/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgbd.forms.dialogs;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sgbd.controllers.Controller;
import sgbd.database.Attribute;
import sgbd.database.Table;

/**
 *
 * @author Alexandre
 */
public class TableDonneesInsertPanel extends javax.swing.JPanel 
{

    /**
     * Creates new form TableDonneesInsertPanel
     * @param laTable
     */
    private Controller controllerInsert;
    private int nbRows = 0;
    private Table laTableInsert;
    private String[][] listeDesValeurs;
    
    public TableDonneesInsertPanel(Table laTable, Controller ctr) 
    {
        initComponents();
        ArrayList<Attribute> lesAttributs = laTable.attributes();
        DefaultTableModel model = (DefaultTableModel) jTableDonneesInsert.getModel();
        for(Attribute attribut : lesAttributs)
        {
            model.addColumn(attribut.getName());
        }
        Object[] rowData = null;
        
        model.addRow(rowData);
        nbRows ++ ;
        
        jTableDonneesInsert.setModel(model);
        
        controllerInsert = ctr;
        
        laTableInsert = laTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDonneesInsert = new javax.swing.JTable();
        jButtonConfirmerInsert = new javax.swing.JButton();

        jTableDonneesInsert.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableDonneesInsert);

        jButtonConfirmerInsert.setText("Confirmer Insert");
        jButtonConfirmerInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmerInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonConfirmerInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonConfirmerInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmerInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmerInsertActionPerformed
        
        listeDesValeurs = new String[jTableDonneesInsert.getRowCount()][jTableDonneesInsert.getColumnCount()];
        for(int col = 0 ; col < jTableDonneesInsert.getColumnCount() ; col++)
        {
            for(int row = 0 ; row < jTableDonneesInsert.getRowCount() ; row++)
            {
                listeDesValeurs[row][col] = jTableDonneesInsert.getValueAt(row, col).toString();
            }
        }
        
        try {
            controllerInsert.addRows(listeDesValeurs, laTableInsert, nbRows);
        } catch (SQLException ex) {
            Logger.getLogger(TableDonneesInsertPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(TableDonneesInsertPanel.this, "Erreur lors de l'insertion de donnéées: " + ex);
        }
    }//GEN-LAST:event_jButtonConfirmerInsertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmerInsert;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDonneesInsert;
    // End of variables declaration//GEN-END:variables
}
