/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgbd.forms;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import sgbd.forms.cardPanels.ConnectionPanel;
import sgbd.forms.cardPanels.VisualizationPanel;

/**
 *
 * @author Kazed
 */
public class CardLayoutPanel extends javax.swing.JPanel {
    private final CardLayout layout;
    /**
     * Creates new form CardLayoutPanel
     */
    public CardLayoutPanel() {
        initComponents();
        layout = (CardLayout)getLayout();
        addPanels();
    }
    
    private void addPanels() {
        add(new ConnectionPanel());
        add(new VisualizationPanel());
        setPanelsParams();
    }
    
    private void setPanelsParams() {
        for(Component comp : getComponents()) {
            switch(comp.getName()) {
                case "visualizationPanel":
                    ((VisualizationPanel)comp).setComponentsParams(getFont());
                    break;
                default :
                    ((ConnectionPanel)comp).setComponentsParams(getFont());
                    break;
            }
        }
    }
    
    private JPanel currentCard() {
        for (Component card : getComponents()) {
            if (card.isVisible() == true) {
             return (JPanel)card;
            }
        }
        return null;
    }

    public JPanel firstCard() {
        layout.first(this);
        return currentCard();
    }
    
    public JPanel lastCard() {
        layout.last(this);
        return currentCard();
    }
    
    public JPanel nextCard() {
        layout.next(this);
        return currentCard();
    }
    
    public JPanel previousCard() {
        layout.previous(this);
        return currentCard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setName("mainPanel"); // NOI18N
        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
